---
layout: cv
title: Resume
---
# Tyler Skalka
Project Manager, System develoepr, Student.

<div id="webaddress">
<a href="tyler.skalka@gmail.com">tyler.skalka@gmail.com</a>
| <a href="https://github.com/Tskalka">My GitHub</a>
</div>

## Summary

Results-oriented Software Developer with experience in Java and JavaScript. Proficient in operating Postman for making
HTTP requests and API testing. Built processes with JSON to transfer data between applications

## Currently

Project Manager - System Developers Brigham Young University Idaho Support Center | Rexburg,
Idaho

 - Managed work of 5 employees to ensure project deliverables were being met

 - Collaborated with other departments daily to create project requests

 - Led weekly developer meetings to overview current projects and set team goals

 - Initiated and conducted weekly one-on-one interviews with team members, facilitating project and code reviews
 to ensure effective progress and quality of deliverables

## Education

`December 2024`
__Bachelor of Science: Computer Science | Brigham Young University - Idaho |
Rexburg, Idaho__

- Programming with Classes
- Programming with Data Structures
- Parallelism and Concurrency
- Machine Learning

## Certifications

`July 2022`
General Programming Certificate | Brigham Young University - Idaho |
Rexburg, Idaho
July 2022

- Applied well-developed design and problem-solving skills
- Demonstrated a firm understanding of principles of programming and software design
- Convert software requirement into code
- Learned and applied new technology and techniques to programming using Python, HTML/CSS, C#

`April 2019`
Microsoft Office Specialist - Excel | Microsoft | Salt Lake City, Utah April 2019

## Skills

- Programming Languages: Java, JavaScript, Python, HTML, CSS
- Object Oriented Programming
- Rest APIs
- Postman
- Data Structures
- Source and version control: Git, GitHub
- Bilingual Spanish - Fluent
- Strong interpersonal communication skills
- Microsoft Office suite (Powerpoint, Word, Excel, Outlook, Teams)

## Projects
`April 2022 - July 2022`
Configuration Manager | Android Mobile Application | Kotlin | Rexburg, Idaho 

- Developed an order of operations calculator with Android Studio and Kotlin
- Managed version control technologies to integrate team's code operating Git and GitHub
- Integrated Python and Java prototypes into Android Studio and Kotlin

<!-- ### Footer

Last updated: May 2013 -->